export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const GET_QTY_CART = 'GET_QTY_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DEACREASE_QUANTITY';
export const DELETE_ITEM = 'DELETE_ITEM';